export enum DocumentTypeIds {
  WARNING_NOTICE = 1,
  CLOSURE_NOTICE = 2,
  CAP_REQUEST = 3,
  SUMMARY_FINDINGS = 4,
  BRIEFING_PAPER = 5,
  CAP_CLOSURE_NOTICE = 6,
  TRANSPARENCY_WORKPAPER = 7,
  CAP_RE_REQUEST = 8
}
