# fly.toml app configuration file generated for biddler-api on 2023-08-17T10:51:18-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "biddler-api"
primary_region = "lax"

[env]
  BIDDLER_DB_DATABASE="BIDDLER_DB"
  BIDDLER_DB_DATABASE_USERNAME="mysql"
  BIDDLER_DB_DATABASE_SERVER="biddler-db.internal"
  BIDDLER_DB_DATABASE_PORT="3306"
  BIDDLER_DB_DIALECT="mysql"

  BIDDLER_IDM_DB_DATABASE="BIDDLER_IDM_DB"
  BIDDLER_IDM_DB_DATABASE_USERNAME="mysql"
  BIDDLER_IDM_DB_DATABASE_SERVER="biddler-idm-db.internal"
  BIDDLER_IDM_DB_DATABASE_PORT="3306"
  BIDDLER_IDM_DB_DIALECT="mysql"

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
