import { ApiPropertyOptional } from '@nestjs/swagger';
import { IsObject, IsString } from 'class-validator';
import { OktaProfile, OktaStrategyOptions } from 'passport-okta-oauth20';

export type OktaAuthModuleOptions = OktaStrategyOptions;

export type OktaAuthGuardOptions = NonNullable<unknown>;

export const oktaGuardDefaultOptions = {};

export interface OktaAuthModuleOptionsFactory {
  createModuleOptions(): Promise<OktaAuthModuleOptions> | OktaAuthModuleOptions;
}

export interface OktaAuthResult {
  originalRequest: Request;
  accessToken: string;
  refreshToken: string;
  profile: OktaProfile;
}

export class CallbackOktaDTO {

  @ApiPropertyOptional({
    description: 'Token generated by okta call',
    example:
      'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkZXN0aW5hdGlvbiI6Im15QGRlc3RpbmF0aW9uLmNvbSIsIm5hbWUiOiJNYXJ5IEphbmUiLCJjb2RlIjoiOTI0MDAiLCJpYXQiOjE2OTQ0NjQ4NzAsImV4cCI6MTY5NDQ2ODQ3MCwiaXNzIjoiYmlkZGxlci1hcGk6bWFnaWMifQ.UN_t4xick15JsR3C6qZfwlOu_xvMMTFkUyCXRNcUBp0'
  })
  @IsString()
  code: string;
}
