CREATE SCHEMA `BIDDLER_IDM_DB` ;
USE `BIDDLER_IDM_DB` ;

-- https://openid.net/specs/openid-connect-core-1_0.html#StandardClaims

-- Record Status
CREATE TABLE BIDDLER_IDM_DB.LKP_INFO (
  LKP_ID          varchar(32)   NOT NULL,
  LKP_CD          VARCHAR(32)   NOT NULL,
  LKP_GRP_NAME    VARCHAR(64)   NOT NULL,
  LKP_TITLE       VARCHAR(128)  DEFAULT NULL,
  LKP_DESC        VARCHAR(256)  DEFAULT NULL,
  LKP_DFLT        BOOL          DEFAULT 0,
  SORT_ORDR       DECIMAL(4,2)  NULL,
  EFCTV_STRT_DT   DATE DEFAULT NULL,
  EFCTV_END_DT    DATE DEFAULT NULL,
  CREATD_DT       DATETIME NOT NULL, 
  CREATD_BY       VARCHAR(48) NULL DEFAULT 'SYSTEM', 
  LAST_UPDATD_DT  DATETIME NOT NULL, 
  LAST_UPDATD_BY  VARCHAR(48) NULL DEFAULT 'SYSTEM', 
  DLTD_AT         DATETIME NULL DEFAULT NULL, 
  PRIMARY KEY (LKP_ID),
  KEY `LKP_INFO_LKP_GRP_NAME_IDX` (`LKP_GRP_NAME`)
) ;

-- Token type
-- CREATE TABLE BIDDLER_IDM_DB.TOKN_TYPE_LKP (
--   TOKN_TYPE_CD  VARCHAR(32) NOT NULL,
--   TYPE_DESC     VARCHAR(64) NULL DEFAULT '{DESCRIPTION MISSING}',
--   CREATD_DT     DATETIME NOT NULL,
--   CREATD_BY     VARCHAR(48) NULL DEFAULT 'SYSTEM',
--   PRIMARY KEY (TOKN_TYPE_CD)
-- ) COMMENT = 'Types of token';

-- Environment
CREATE TABLE BIDDLER_IDM_DB.ENV_INFO (
  ENV_INFO_CD   VARCHAR(32)   NOT NULL,
  STUS_LKP_ID   VARCHAR(32)   NOT NULL,
  ENV_DESC      VARCHAR(64)   NULL DEFAULT 'Environment description',
  ENV_ALIASES     VARCHAR(512)  NOT NULL COMMENT 'Space delimited array of possible names for a given environment (ex. dev, development)',
  CREATD_DT       DATETIME NOT NULL, 
  CREATD_BY       VARCHAR(48) NULL DEFAULT 'SYSTEM', 
  LAST_UPDATD_DT  DATETIME NOT NULL, 
  LAST_UPDATD_BY  VARCHAR(48) NULL DEFAULT 'SYSTEM', 
  DLTD_AT         DATETIME NULL DEFAULT NULL, 
  PRIMARY KEY (ENV_INFO_CD),
  CONSTRAINT ENV_INFO_FK FOREIGN KEY (STUS_LKP_ID) REFERENCES BIDDLER_IDM_DB.LKP_INFO(LKP_ID)
) COMMENT = 'Represents all possible environments of a given application';

-- Application Info 
CREATE TABLE BIDDLER_IDM_DB.SYS_INFO (
	SYS_ID              INT auto_increment NOT NULL,
  STUS_LKP_ID         VARCHAR(32)   NOT NULL,
	SYS_NAME            VARCHAR(64) NOT NULL,
  SYS_NAME_SLUG       VARCHAR(96) NOT NULL,
  SYS_DESC            VARCHAR(256) NULL,
  SYS_URL             VARCHAR(256) NULL COMMENT 'Application web address',
	EFCTV_STRT_DT       TIMESTAMP NULL,
	EFCTV_END_DT        TIMESTAMP NULL,
  CREATD_DT           DATETIME NOT NULL, 
  CREATD_BY           VARCHAR(48) NULL DEFAULT 'SYSTEM', 
  LAST_UPDATD_DT      DATETIME NOT NULL, 
  LAST_UPDATD_BY      VARCHAR(48) NULL DEFAULT 'SYSTEM', 
  DLTD_AT             DATETIME NULL DEFAULT NULL, 
  CONSTRAINT SYS_INFO_PK PRIMARY KEY (SYS_ID),
	CONSTRAINT SYS_INFO_FK FOREIGN KEY (STUS_LKP_ID) REFERENCES BIDDLER_IDM_DB.LKP_INFO(LKP_ID)
) COMMENT = 'Parent table of a particular application';

-- Application Feature
-- CREATE TABLE BIDDLER_IDM_DB.SYS_FEATURE (
-- 	SYS_FEATURE_ID      INT auto_increment NOT NULL,
--   SYS_ID              INT NOT NULL,
--   STUS_LKP_ID         VARCHAR(32) NOT NULL,
-- 	FEATURE_NAME        VARCHAR(64) NOT NULL,
--   FEATURE_SLUG        VARCHAR(256) NULL COMMENT 'Slug of system feature name (ex. read-review',
-- 	EFCTV_STRT_DT       TIMESTAMP NULL,
-- 	EFCTV_END_DT        TIMESTAMP NULL,
--   CREATD_DT           DATETIME NOT NULL,
-- 	CREATD_BY           VARCHAR(48) NULL DEFAULT 'SYSTEM',
-- 	LAST_UPDATD_DT      DATETIME NOT NULL,
-- 	LAST_UPDATD_BY      VARCHAR(48) NULL DEFAULT 'SYSTEM',
--   DLTD_AT             DATETIME NULL DEFAULT NULL,
--   CONSTRAINT SYS_FEATURE_PK PRIMARY KEY (SYS_FEATURE_ID),
-- 	CONSTRAINT SYS_FEATURE_FK FOREIGN KEY (STUS_LKP_ID) REFERENCES BIDDLER_IDM_DB.LKP_INFO(LKP_ID),
--   CONSTRAINT SYS_FEATURE_FK_1 FOREIGN KEY (SYS_ID) REFERENCES BIDDLER_IDM_DB.SYS_INFO(SYS_ID) ON DELETE CASCADE ON UPDATE CASCADE
-- ) COMMENT = 'System Feature Management.  Primarily used for turning features on and off';

-- CREATE TABLE BIDDLER_IDM_DB.SYS_FEATURE_ENV (
-- 	SYS_FEATURE_ID      INT NOT NULL,
--   ENV_INFO_CD         VARCHAR(32) NOT NULL,
--   STUS_LKP_ID         VARCHAR(32) NOT NULL,
-- 	EFCTV_STRT_DT       TIMESTAMP NULL,
-- 	EFCTV_END_DT        TIMESTAMP NULL,
--   CREATD_DT           DATETIME NOT NULL,
-- 	CREATD_BY           VARCHAR(48) NULL DEFAULT 'SYSTEM',
--   CONSTRAINT SYS_FEATURE_ENV_PK PRIMARY KEY (SYS_FEATURE_ID, ENV_INFO_CD),
-- 	CONSTRAINT SYS_FEATURE_ENV_FK FOREIGN KEY (STUS_LKP_ID) REFERENCES BIDDLER_IDM_DB.LKP_INFO(LKP_ID),
--   CONSTRAINT SYS_FEATURE_ENV_FK_1 FOREIGN KEY (SYS_FEATURE_ID) REFERENCES BIDDLER_IDM_DB.SYS_FEATURE(SYS_FEATURE_ID) ON DELETE CASCADE ON UPDATE CASCADE,
--   CONSTRAINT SYS_FEATURE_ENV_FK_2 FOREIGN KEY (ENV_INFO_CD) REFERENCES BIDDLER_IDM_DB.ENV_INFO(ENV_INFO_CD)
-- ) COMMENT = 'System feature environments.  Illustrates which features of an system are enabled in which environments';

CREATE TABLE BIDDLER_IDM_DB.APLCTN_INFO (
  APLCTN_ID           INT auto_increment NOT NULL, 
  STUS_LKP_ID         VARCHAR(32) NOT NULL,
  APLCTN_NAME         VARCHAR(64) NOT NULL,
  APLCTN_DESC         VARCHAR(128) NOT NULL,
  CREATD_DT           DATETIME NOT NULL,
	CREATD_BY           VARCHAR(48) NULL DEFAULT 'SYSTEM',
	LAST_UPDATD_DT      DATETIME NOT NULL,
	LAST_UPDATD_BY      VARCHAR(48) NULL DEFAULT 'SYSTEM',
  DLTD_AT             DATETIME NULL DEFAULT NULL,
  CONSTRAINT APLCTN_INFO_PK PRIMARY KEY (APLCTN_ID),
  CONSTRAINT APLCTN_INFO_FK FOREIGN KEY (STUS_LKP_ID) REFERENCES BIDDLER_IDM_DB.LKP_INFO(LKP_ID)
) COMMENT = 'Registered applications for api access';


-- Application Authorization scope
-- CREATE TABLE BIDDLER_IDM_DB.APLCTN_SCOPE (
--   APLCTN_SCOPE_ID     INT auto_increment NOT NULL,
-- 	APLCTN_ID           INT NOT NULL,
--   STUS_LKP_ID        VARCHAR(32) NOT NULL,
-- 	SCOPE_NAME          VARCHAR(64) NOT NULL,
--   PREFIX_SW           BIT NOT NULL DEFAULT 0 COMMENT '(1) when scope is prefix (no claims); otherwise 0: false',
--   CREATD_DT           DATETIME NOT NULL,
-- 	CREATD_BY           VARCHAR(48) NULL DEFAULT 'SYSTEM',
-- 	LAST_UPDATD_DT      DATETIME NOT NULL,
-- 	LAST_UPDATD_BY      VARCHAR(48) NULL DEFAULT 'SYSTEM',
--   DLTD_AT             DATETIME NULL DEFAULT NULL,
--   CONSTRAINT APLCTN_SCOPE_PK PRIMARY KEY (APLCTN_SCOPE_ID),
-- 	CONSTRAINT APLCTN_SCOPE_FK FOREIGN KEY (STUS_LKP_ID) REFERENCES BIDDLER_IDM_DB.LKP_INFO(LKP_ID), 
--   CONSTRAINT APLCTN_SCOPE_FK_1 FOREIGN KEY (APLCTN_ID) REFERENCES BIDDLER_IDM_DB.APLCTN_INFO(APLCTN_ID) ON DELETE CASCADE ON UPDATE CASCADE
-- ) COMMENT = 'Application scope manager.  Contains an application''s entire list of available scopes.  Subsets of these scopes are usually contained in the application issuer scope table.';

-- ISSUER
CREATE TABLE BIDDLER_IDM_DB.SYS_ISSUER (
	SYS_ISSUER_ID       INT auto_increment NOT NULL,
  SYS_ID              INT NOT NULL,
  STUS_LKP_ID         VARCHAR(32) NOT NULL,
  TOKN_TYP_LKP_ID     VARCHAR(32) NOT NULL DEFAULT 'bearer' COMMENT 'Type of token: Default to ''bearer''',
	ISSUER_NAME         VARCHAR(128) NOT NULL COMMENT 'Issuer Identifier for the Issuer of the response.',
  TKN_TTL             INT NOT NULL COMMENT '(Time-To-Live) Maximum amount of time (minutes) ACCESS token has to live in application',
  RFRSH_TKN_TTL       INT NULL COMMENT '(Time-To-Live) Maximum amount of time (minutes) REFRESH token has to live in application',
  HASH_ALGORITHM      VARCHAR(32) NULL COMMENT 'Algorithm to use when generating tokens',
  ORIGIN              VARCHAR(1024) NULL DEFAULT '*' COMMENT 'CORS ORIGIN Space delimited array of URLs, IP addresses and/or IP Address ranges.  If blank or ''*'' then all are allowed, otherwise ONLY listed IP addresses allowed',
  RESTRICTED_IPS      VARCHAR(1024) NULL COMMENT 'Space delimited array of IP addresses and/or IP Address ranges that are restricted',
  ALLOWED_IPS         VARCHAR(1024) NULL COMMENT 'Space delimited array of IP addresses and/or IP Address ranges that are allowed',
  METHODS             VARCHAR(512) NULL COMMENT 'Configures the Access-Control-Allow-Methods CORS header. Expects a comma-delimited string (ex: ''GET,PUT,POST'')',  
  ALLOWED_HEADERS     VARCHAR(512) NULL COMMENT 'Configures the Access-Control-Allow-Headers CORS header. Expects a comma-delimited string (ex: ''Content-Type,Authorization'')',  
  EXPOSED_HEADERS     VARCHAR(512) NULL COMMENT 'Configures the Access-Control-Expose-Headers CORS header. Expects a comma-delimited string (ex: ''Content-Range,X-Content-Range'')', 
  ALLOW_CREDENTIALS   BIT NULL DEFAULT 1 COMMENT 'Configures the Access-Control-Allow-Credentials CORS header. Setting to true passes header, otherwise it is omitted', 
  MAX_AGE_SECONDS     INT NULL COMMENT 'The Access-Control-Max-Age response header indicates how long the results of a preflight request (that is the information contained in the Access-Control-Allow-Methods and Access-Control-Allow-Headers headers) can be cached',
  CREATD_DT           DATETIME NOT NULL,
	CREATD_BY           VARCHAR(48) NULL DEFAULT 'SYSTEM',
	LAST_UPDATD_DT      DATETIME NOT NULL,
	LAST_UPDATD_BY      VARCHAR(48) NULL DEFAULT 'SYSTEM',
  DLTD_AT             DATETIME NULL DEFAULT NULL,
  CONSTRAINT SYS_ISSUER_PK    PRIMARY KEY (SYS_ISSUER_ID),
	CONSTRAINT SYS_ISSUER_FK    FOREIGN KEY (STUS_LKP_ID) REFERENCES BIDDLER_IDM_DB.LKP_INFO(LKP_ID),
  CONSTRAINT SYS_ISSUER_FK_1  FOREIGN KEY (TOKN_TYP_LKP_ID) REFERENCES BIDDLER_IDM_DB.LKP_INFO(LKP_ID),
  CONSTRAINT SYS_ISSUER_FK_2  FOREIGN KEY (SYS_ID) REFERENCES BIDDLER_IDM_DB.SYS_INFO(SYS_ID) ON DELETE CASCADE ON UPDATE CASCADE
) COMMENT='The system token issuer manager.  A system can contain multiple issuers with different configurations defined depending on client needs';


-- CLIENT
CREATE TABLE BIDDLER_IDM_DB.API_CLIENT (
	API_CLIENT_ID       CHAR(36) NOT NULL,
  APLCTN_ID           INT NOT NULL,
  SYS_ISSUER_ID       INT NOT NULL,
  TOKN_TYP_LKP_ID     VARCHAR(32) NOT NULL COMMENT 'Type of token issued to client',
  STUS_LKP_ID         VARCHAR(32) NOT NULL,
  CLIENT_AUD          VARCHAR(48) NULL COMMENT 'Audience (aud) that this ID Token is intended for.',
	CLIENT_SUB          CHAR(36) NULL COMMENT 'Subject Identifier (sub) on token. A locally unique and never reassigned identifier within the Issuer for the End-User, which is intended to be consumed by the Client. ',
  KEY_SECRET_HASH     VARCHAR(128) NULL COMMENT 'Client secret key HASH for generating access tokens', 
  KEY_SALT            VARCHAR(255) NULL COMMENT 'Client secret key salt used to formulate access tokens',
  SCOPES              VARCHAR(2048) NULL COMMENT 'Space-delimited array of scopes',
  ALLOWED_IPS         VARCHAR(1024) NOT NULL DEFAULT '*' COMMENT 'Space delimited array of IP addresses and/or IP Address ranges.  If blank or ''*'' then all are allowed, otherwise ONLY listed IP addresses allowed',
  RESTRICTED_IPS      VARCHAR(1024) NOT NULL DEFAULT '-' COMMENT 'Space delimited array of IP addresses and/or IP Address ranges that are restricted. If blank or ''-'' then there are no restrictions',  
  TKN_TTL             INT NULL COMMENT '(Time-To-Live) Maximum amount of time (seconds) ACCESS token has to live in application',
  RFRSH_TKN_TTL       INT NULL COMMENT '(Time-To-Live) Maximum amount of time (seconds) REFRESH token has to live in application',
  CREATD_DT           DATETIME NOT NULL,
	CREATD_BY           VARCHAR(48) NULL DEFAULT 'SYSTEM',
	LAST_UPDATD_DT      DATETIME NOT NULL,
	LAST_UPDATD_BY      VARCHAR(48) NULL DEFAULT 'SYSTEM',
  DLTD_AT             DATETIME NULL DEFAULT NULL,
  CONSTRAINT API_CLIENT_PK    PRIMARY KEY (API_CLIENT_ID),
	CONSTRAINT API_CLIENT_FK    FOREIGN KEY (STUS_LKP_ID) REFERENCES BIDDLER_IDM_DB.LKP_INFO(LKP_ID),
  CONSTRAINT API_CLIENT_FK_1  FOREIGN KEY (TOKN_TYP_LKP_ID) REFERENCES BIDDLER_IDM_DB.LKP_INFO(LKP_ID),
  CONSTRAINT API_CLIENT_FK_2  FOREIGN KEY (APLCTN_ID) REFERENCES BIDDLER_IDM_DB.APLCTN_INFO(APLCTN_ID) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT API_CLIENT_FK_3  FOREIGN KEY (SYS_ISSUER_ID) REFERENCES BIDDLER_IDM_DB.SYS_ISSUER(SYS_ISSUER_ID) ON DELETE CASCADE ON UPDATE CASCADE
) COMMENT='The applications'' client manager for identity management';

-- CREATE TABLE BIDDLER_IDM_DB.ACNT_INFO (
--   ACNT_ID         INT NOT NULL AUTO_INCREMENT,
--   STUS_LKP_ID     VARCHAR(32) NOT NULL,
--   ACNT_NAME       VARCHAR(48) NOT NULL,
--   CREATD_DT       DATETIME NOT NULL, 
--   CREATD_BY       VARCHAR(48) NULL DEFAULT 'SYSTEM', 
--   LAST_UPDATD_DT  DATETIME NOT NULL, 
--   LAST_UPDATD_BY  VARCHAR(48) NULL DEFAULT 'SYSTEM', 
--   DLTD_AT         DATETIME NULL DEFAULT NULL, 
--   CONSTRAINT ACNT_INFO_PK PRIMARY KEY (ACNT_ID),
--   CONSTRAINT ACNT_INFO_FK FOREIGN KEY (STUS_LKP_ID) REFERENCES BIDDLER_IDM_DB.LKP_INFO(LKP_ID)
-- );

-- CREATE TABLE BIDDLER_IDM_DB.PERMSN_INFO (
--   PERMSN_ID     VARCHAR(32) NOT NULL,
--   STUS_LKP_ID   VARCHAR(32) NOT NULL,
--   PERMSN_DESC   VARCHAR(128) DEFAULT NULL,
--   CREATD_DT     DATETIME NOT NULL, 
--   CREATD_BY     VARCHAR(48) NULL DEFAULT 'SYSTEM',
--   DLTD_AT       DATETIME NULL DEFAULT NULL, 
--   CONSTRAINT PERMSN_INFO_PK PRIMARY KEY (PERMSN_ID),
--   CONSTRAINT PERMSN_INFO_FK FOREIGN KEY (STUS_LKP_ID) REFERENCES BIDDLER_IDM_DB.LKP_INFO(LKP_ID)
-- ) ;

-- CREATE TABLE BIDDLER_IDM_DB.ROLE_INFO (
--   ROLE_ID       VARCHAR(32)   NOT NULL,
--   STUS_LKP_ID  VARCHAR(32)   NOT NULL,
--   ROLE_DESC     VARCHAR(128)  DEFAULT NULL,
--   CREATD_DT     DATETIME      NOT NULL, 
--   CREATD_BY     VARCHAR(48)   NULL DEFAULT 'SYSTEM', 
--   DLTD_AT       DATETIME      NULL DEFAULT NULL, 
--   CONSTRAINT ROLE_INFO_PK PRIMARY KEY (ROLE_ID),
--   CONSTRAINT ROLE_INFO_FK FOREIGN KEY (STUS_LKP_ID) REFERENCES BIDDLER_IDM_DB.LKP_INFO(LKP_ID)
-- );

-- CREATE TABLE BIDDLER_IDM_DB.ROLE_PERMSN (
--   PERMSN_ID       VARCHAR(32) NOT NULL,
--   ROLE_ID         VARCHAR(32) NOT NULL,
--   STUS_LKP_ID     VARCHAR(32) NOT NULL,
--   EFCTV_STRT_DT   DATE DEFAULT NULL,
--   EFCTV_END_DT    DATE DEFAULT NULL,
--   CREATD_DT       DATETIME NOT NULL, 
--   CREATD_BY       VARCHAR(48) NULL DEFAULT 'SYSTEM', 
--   LAST_UPDATD_DT  DATETIME NOT NULL, 
--   LAST_UPDATD_BY  VARCHAR(48) NULL DEFAULT 'SYSTEM', 
--   DLTD_AT         DATETIME NULL DEFAULT NULL, 
--   CONSTRAINT ROLE_PERMSN_PK   PRIMARY KEY (PERMSN_ID, ROLE_ID),
--   CONSTRAINT ROLE_PERMSN_FK   FOREIGN KEY (PERMSN_ID) REFERENCES BIDDLER_IDM_DB.PERMSN_INFO (PERMSN_ID) ON DELETE CASCADE ON UPDATE RESTRICT,
--   CONSTRAINT ROLE_PERMSN_FK_1 FOREIGN KEY (ROLE_ID)  REFERENCES BIDDLER_IDM_DB.ROLE_INFO (ROLE_ID) ON DELETE CASCADE ON UPDATE RESTRICT,
--   CONSTRAINT ROLE_PERMSN_FK_2 FOREIGN KEY (STUS_LKP_ID)  REFERENCES BIDDLER_IDM_DB.LKP_INFO (LKP_ID)
-- ) ;


CREATE TABLE BIDDLER_IDM_DB.USER_INFO (
  USER_ID         INT NOT NULL AUTO_INCREMENT,
  STUS_LKP_ID     VARCHAR(32) NOT NULL,
  FIRST_NAME      VARCHAR(32) NULL,
  LAST_NAME       VARCHAR(64) NULL,
  USER_NAME       VARCHAR(256) NOT NULL,
  EMAIL           VARCHAR(256) NOT NULL,
  SALT            CHAR(64) NULL,
  PWD             CHAR(64) NULL,
  CREATD_DT       DATETIME NOT NULL, 
  CREATD_BY       VARCHAR(48) NULL DEFAULT 'SYSTEM', 
  LAST_UPDATD_DT  DATETIME NOT NULL, 
  LAST_UPDATD_BY  VARCHAR(48) NULL DEFAULT 'SYSTEM', 
  DLTD_AT         DATETIME NULL DEFAULT NULL, 
  CONSTRAINT USER_INFO_PK PRIMARY KEY (USER_ID),
  CONSTRAINT USER_INFO_FK FOREIGN KEY (STUS_LKP_ID) REFERENCES BIDDLER_IDM_DB.LKP_INFO(LKP_ID)
) ;


-- CREATE TABLE BIDDLER_IDM_DB.ACNT_USER (
--   ACNT_ID           INT NOT NULL,
--   USER_ID           INT NOT NULL,
--   STUS_LKP_ID       VARCHAR(32) NOT NULL,
--   EFCTV_STRT_DT     DATE DEFAULT NULL,
--   EFCTV_END_DT      DATE DEFAULT NULL,
--   CREATD_DT         DATETIME NOT NULL, 
--   CREATD_BY         VARCHAR(48) NULL DEFAULT 'SYSTEM', 
--   LAST_UPDATD_DT    DATETIME NOT NULL, 
--   LAST_UPDATD_BY    VARCHAR(48) NULL DEFAULT 'SYSTEM', 
--   DLTD_AT           DATETIME NULL DEFAULT NULL, 
--   CONSTRAINT ACNT_USER_PK PRIMARY KEY (USER_ID, ACNT_ID), 
--   CONSTRAINT ACNT_USER_FK FOREIGN KEY (ACNT_ID) REFERENCES BIDDLER_IDM_DB.ACNT_INFO (ACNT_ID) ON DELETE CASCADE,
--   CONSTRAINT ACNT_USER_FK_1 FOREIGN KEY (USER_ID) REFERENCES BIDDLER_IDM_DB.USER_INFO (USER_ID) ON DELETE CASCADE,
--   CONSTRAINT ACNT_USER_FK_2 FOREIGN KEY (STUS_LKP_ID) REFERENCES BIDDLER_IDM_DB.LKP_INFO (LKP_ID)
-- );

-- CREATE TABLE BIDDLER_IDM_DB.USER_ROLES (
--   USER_ID           INT NOT NULL,
--   ROLE_ID           VARCHAR(24) NOT NULL,
--   STUS_LKP_ID       VARCHAR(32) NOT NULL,
--   EFCTV_STRT_DT     DATE DEFAULT NULL,
--   EFCTV_END_DT      DATE DEFAULT NULL,
--   CREATD_DT         DATETIME NOT NULL,
-- 	CREATD_BY         VARCHAR(48) NULL DEFAULT 'SYSTEM',
-- 	LAST_UPDATD_DT    DATETIME NOT NULL,
-- 	LAST_UPDATD_BY    VARCHAR(48) NULL DEFAULT 'SYSTEM',
--   DLTD_AT           DATETIME NULL DEFAULT NULL,
--   PRIMARY KEY (USER_ID, ROLE_ID),
--   CONSTRAINT USER_ROLES_FK_1 FOREIGN KEY (USER_ID) REFERENCES BIDDLER_IDM_DB.USER_INFO (USER_ID) ON DELETE CASCADE,
--   CONSTRAINT USER_ROLES_FK_2 FOREIGN KEY (ROLE_ID) REFERENCES BIDDLER_IDM_DB.ROLE_INFO (ROLE_ID) ON DELETE CASCADE ON UPDATE CASCADE,
--   CONSTRAINT USER_ROLES_FK_3 FOREIGN KEY (STUS_LKP_ID) REFERENCES BIDDLER_IDM_DB.LKP_INFO (LKP_ID)
-- ) ;

-- CREATE TABLE BIDDLER_IDM_DB.RSRC_INFO (
--   RSRC_ID             INT auto_increment NOT NULL,
--   STUS_LKP_ID         VARCHAR(32) NOT NULL,
--   RSRC_REL_PATH       VARCHAR(256) NOT NULL COMMENT 'Relative path of resource (i.e. /*/*/health-check | /storage/uploadFile)', 
--   RSRC_HTTP_VERB      VARCHAR(128) NOT NULL COMMENT 'Comma delimited list of HTTP VERBS (i.e. GET, POST, PUT, DELETE, PATCH, etc)',
--   EFCTV_STRT_DT       DATE DEFAULT NULL,
--   EFCTV_END_DT        DATE DEFAULT NULL,
--   CREATD_DT            DATETIME NOT NULL,
-- 	CREATD_BY            VARCHAR(48) NULL DEFAULT 'SYSTEM',
-- 	LAST_UPDATD_DT       DATETIME NOT NULL,
-- 	LAST_UPDATD_BY       VARCHAR(48) NULL DEFAULT 'SYSTEM',
--   DLTD_AT              DATETIME NULL DEFAULT NULL,
--   PRIMARY KEY (RSRC_ID),
--   CONSTRAINT RSRC_INFO_FK FOREIGN KEY (STUS_LKP_ID) REFERENCES BIDDLER_IDM_DB.LKP_INFO(LKP_ID)
-- ) ;


-- CREATE TABLE BIDDLER_IDM_DB.ACNT_USER_ROLE (
--   ACNT_ID           INT NOT NULL,
--   USER_ID           INT NOT NULL,
--   ROLE_ID           VARCHAR(32) NOT NULL,
--   STUS_LKP_ID       VARCHAR(32) NOT NULL,
--   EFCTV_STRT_DT     DATE DEFAULT NULL,
--   EFCTV_END_DT      DATE DEFAULT NULL,
--   CREATD_DT         DATETIME NOT NULL, 
--   CREATD_BY         VARCHAR(48) NULL DEFAULT 'SYSTEM', 
--   LAST_UPDATD_DT    DATETIME NOT NULL, 
--   LAST_UPDATD_BY    VARCHAR(48) NULL DEFAULT 'SYSTEM', 
--   DLTD_AT           DATETIME NULL DEFAULT NULL, 
--   CONSTRAINT ACNT_USER_ROLE_PK    PRIMARY KEY (USER_ID,ACNT_ID,ROLE_ID),
--   CONSTRAINT ACNT_USER_ROLE_FK    FOREIGN KEY (ACNT_ID) REFERENCES BIDDLER_IDM_DB.ACNT_INFO (ACNT_ID) ON DELETE CASCADE,
--   CONSTRAINT ACNT_USER_ROLE_FK_1  FOREIGN KEY (USER_ID) REFERENCES BIDDLER_IDM_DB.USER_INFO (USER_ID) ON DELETE CASCADE,
--   CONSTRAINT ACNT_USER_ROLE_FK_2  FOREIGN KEY (ROLE_ID) REFERENCES BIDDLER_IDM_DB.ROLE_INFO (ROLE_ID) ON DELETE CASCADE ON UPDATE CASCADE,
--   CONSTRAINT ACNT_USER_ROLE_FK_3  FOREIGN KEY (STUS_LKP_ID)  REFERENCES BIDDLER_IDM_DB.LKP_INFO  (LKP_ID)
-- ) ;

-- Although the tables are created earlier in the script we may eventually want to add these tables
-- When that is the case simply comment out the lines below
-- DROP TABLE ACNT_USERS;
-- DROP TABLE ACNT_USR_ROLES;
-- DROP TABLE ACNT_INFO;

-- Environment
CREATE TABLE BIDDLER_IDM_DB.ACS_TOKN (
  ACS_TOKN_ID     INT auto_increment NOT NULL,
  USER_ID         INT NULL COMMENT 'User Id',
  STUS_LKP_ID     VARCHAR(32) NOT NULL,
  TOKN_TYP_LKP_ID  VARCHAR(32) NOT NULL COMMENT 'self-signed jwt, access, id, refresh, bearer, federated',
  SCHM_TYP_LKP_ID VARCHAR(32) DEFAULT 'tst_ascii' NOT NULL COMMENT 'pci, ascii',
  TKN             VARCHAR(1024) NOT NULL COMMENT 'Access token',
  TKN_SCRT        VARCHAR(512) NULL COMMENT 'Access token secret',
  SCOPE           VARCHAR(256) NULL,
  EXPIRS_IN       INT NULL DEFAULT 3600,
  ORIGN           VARCHAR(256) DEFAULT '*',
  FRCE_RFRSH      BOOL DEFAULT 1,
  IP_ADRS         VARCHAR(64) NULL COMMENT 'IP Address (if Applicable) of token issuee',
  COOKIE          VARCHAR(512) NULL,
  EXPIR_DT        DATETIME NULL,
  ISSUED_DT       DATETIME NULL,
  CREATD_DT       DATETIME NOT NULL, 
  CREATD_BY       VARCHAR(48) NULL DEFAULT 'SYSTEM', 
  LAST_UPDATD_DT  DATETIME NOT NULL, 
  LAST_UPDATD_BY  VARCHAR(48) NULL DEFAULT 'SYSTEM', 
  DLTD_AT         DATETIME NULL DEFAULT NULL, 
  PRIMARY KEY (ACS_TOKN_ID),
  CONSTRAINT ACS_TOKN_FK    FOREIGN KEY (STUS_LKP_ID)      REFERENCES BIDDLER_IDM_DB.LKP_INFO(LKP_ID),
  CONSTRAINT ACS_TOKN_FK_1  FOREIGN KEY (TOKN_TYP_LKP_ID)   REFERENCES BIDDLER_IDM_DB.LKP_INFO(LKP_ID),
  CONSTRAINT ACS_TOKN_FK_2  FOREIGN KEY (SCHM_TYP_LKP_ID)  REFERENCES BIDDLER_IDM_DB.LKP_INFO(LKP_ID),
  CONSTRAINT ACS_TOKN_FK_3  FOREIGN KEY (USER_ID)  REFERENCES BIDDLER_IDM_DB.USER_INFO(USER_ID)
) COMMENT = 'Access token for different authentication forms';