CREATE SCHEMA IF NOT EXISTS BIDDLER_DB;

CREATE TABLE BIDDLER_DB.LKP_INFO (
  LKP_CD          VARCHAR(32)   NOT NULL,
  LKP_GRP_NAME    VARCHAR(64)   NULL,
  LKP_TITLE       VARCHAR(128)  DEFAULT NULL,
  LKP_DESC        VARCHAR(64)   DEFAULT NULL,
  LKP_DFLT        VARCHAR(64)   DEFAULT NULL,
  SORT_ORDR       DECIMAL(4,2)  NULL,
  CREATD_DT       DATETIME NOT NULL, 
  CREATD_BY       VARCHAR(48) NULL DEFAULT 'SYSTEM', 
  LAST_UPDATD_DT  DATETIME NOT NULL, 
  LAST_UPDATD_BY  VARCHAR(48) NULL DEFAULT 'SYSTEM', 
  DLTD_AT         DATETIME NULL DEFAULT NULL, 
  CONSTRAINT LKP_INFO_PK PRIMARY KEY (LKP_CD)
) ;

CREATE TABLE BIDDLER_DB.ACNT_INFO (
  ACNT_ID         INT NOT NULL AUTO_INCREMENT,
  STUS_LKP_CD     VARCHAR(32) NOT NULL,
  ACNT_NAME       VARCHAR(48) NOT NULL,
  CREATD_DT       DATETIME NOT NULL, 
  CREATD_BY       VARCHAR(48) NULL DEFAULT 'SYSTEM', 
  LAST_UPDATD_DT  DATETIME NOT NULL, 
  LAST_UPDATD_BY  VARCHAR(48) NULL DEFAULT 'SYSTEM', 
  DLTD_AT         DATETIME NULL DEFAULT NULL, 
  CONSTRAINT ACNT_INFO_PK PRIMARY KEY (ACNT_ID),
  CONSTRAINT ACNT_INFO_FK FOREIGN KEY (STUS_LKP_CD) REFERENCES BIDDLER_DB.LKP_INFO(LKP_CD)
);

CREATE TABLE BIDDLER_DB.PERMSN_INFO (
  PERMSN_ID     VARCHAR(32) NOT NULL,
  STUS_LKP_CD   VARCHAR(32) NOT NULL,
  PERMSN_DESC   VARCHAR(128) DEFAULT NULL,
  CREATD_DT     DATETIME NOT NULL, 
  CREATD_BY     VARCHAR(48) NULL DEFAULT 'SYSTEM',
  DLTD_AT       DATETIME NULL DEFAULT NULL, 
  CONSTRAINT PERMSN_INFO_PK PRIMARY KEY (PERMSN_ID),
  CONSTRAINT PERMSN_INFO_FK FOREIGN KEY (STUS_LKP_CD) REFERENCES BIDDLER_DB.LKP_INFO(LKP_CD)
) ;

CREATE TABLE BIDDLER_DB.ROLE_INFO (
  ROLE_ID       VARCHAR(32)   NOT NULL,
  STUS_LKP_CD  VARCHAR(32)   NOT NULL,
  ROLE_DESC     VARCHAR(128)  DEFAULT NULL,
  CREATD_DT     DATETIME      NOT NULL, 
  CREATD_BY     VARCHAR(48)   NULL DEFAULT 'SYSTEM', 
  DLTD_AT       DATETIME      NULL DEFAULT NULL, 
  CONSTRAINT ROLE_INFO_PK PRIMARY KEY (ROLE_ID),
  CONSTRAINT ROLE_INFO_FK FOREIGN KEY (STUS_LKP_CD) REFERENCES BIDDLER_DB.LKP_INFO(LKP_CD)
);

CREATE TABLE BIDDLER_DB.ADDR_INFO (
  ADR_ID          INT NOT NULL AUTO_INCREMENT,
  STUS_LKP_CD     VARCHAR(32) NOT NULL,
  ADR_TYPE_LKP_CD VARCHAR(32) NOT NULL,
  ADR_LINE_1      VARCHAR(128) NOT NULL,
  ADR_LINE_2      VARCHAR(128) DEFAULT NULL,
  ADR_LINE_3      VARCHAR(128) DEFAULT NULL,
  CITY            VARCHAR(56) DEFAULT NULL,
  STATE           VARCHAR(48) DEFAULT NULL,
  CNTY            VARCHAR(96) DEFAULT NULL,
  CNTRY           VARCHAR(96) DEFAULT NULL,
  PSTL_CD             VARCHAR(20) DEFAULT NULL,
  LAT                 DECIMAL(8,6) DEFAULT NULL,
  LON                 DECIMAL(9,6) DEFAULT NULL,
  CREATD_DT           DATETIME NOT NULL, 
  CREATD_BY           VARCHAR(48) NULL DEFAULT 'SYSTEM', 
  LAST_UPDATD_DT      DATETIME NOT NULL, 
  LAST_UPDATD_BY      VARCHAR(48) NULL DEFAULT 'SYSTEM', 
  DLTD_AT             DATETIME NULL DEFAULT NULL, 
  CONSTRAINT ADDR_INFO_PK   PRIMARY KEY (ADR_ID), 
  CONSTRAINT ADDR_INFO_FK   FOREIGN KEY (STUS_LKP_CD) REFERENCES BIDDLER_DB.LKP_INFO(LKP_CD),
  CONSTRAINT ADDR_INFO_FK_1 FOREIGN KEY (ADR_TYPE_LKP_CD) REFERENCES BIDDLER_DB.LKP_INFO(LKP_CD)
) ;

CREATE TABLE BIDDLER_DB.USER_INFO (
  USER_ID         INT NOT NULL AUTO_INCREMENT,
  STUS_LKP_CD    VARCHAR(32) NOT NULL,
  FIRST_NAME      VARCHAR(32) NOT NULL,
  LAST_NAME       VARCHAR(64) NOT NULL,
  EMAIL           VARCHAR(64) NOT NULL,
  CREATD_DT       DATETIME NOT NULL, 
  CREATD_BY       VARCHAR(48) NULL DEFAULT 'SYSTEM', 
  LAST_UPDATD_DT  DATETIME NOT NULL, 
  LAST_UPDATD_BY  VARCHAR(48) NULL DEFAULT 'SYSTEM', 
  DLTD_AT         DATETIME NULL DEFAULT NULL, 
  CONSTRAINT USER_INFO_PK PRIMARY KEY (USER_ID),
  CONSTRAINT USER_INFO_FK FOREIGN KEY (STUS_LKP_CD) REFERENCES BIDDLER_DB.LKP_INFO(LKP_CD)
) ;

CREATE TABLE BIDDLER_DB.ACNT_USER (
  ACNT_ID           INT NOT NULL,
  USER_ID           INT NOT NULL,
  STUS_LKP_CD      VARCHAR(32) NOT NULL,
  EFCTV_STRT_DT     DATE DEFAULT NULL,
  EFCTV_END_DT      DATE DEFAULT NULL,
  CREATD_DT         DATETIME NOT NULL, 
  CREATD_BY         VARCHAR(48) NULL DEFAULT 'SYSTEM', 
  LAST_UPDATD_DT    DATETIME NOT NULL, 
  LAST_UPDATD_BY    VARCHAR(48) NULL DEFAULT 'SYSTEM', 
  DLTD_AT           DATETIME NULL DEFAULT NULL, 
  CONSTRAINT ACNT_USER_PK PRIMARY KEY (USER_ID, ACNT_ID), 
  CONSTRAINT ACNT_USER_FK FOREIGN KEY (ACNT_ID) REFERENCES BIDDLER_DB.ACNT_INFO (ACNT_ID) ON DELETE CASCADE,
  CONSTRAINT ACNT_USER_FK_1 FOREIGN KEY (USER_ID) REFERENCES BIDDLER_DB.USER_INFO (USER_ID) ON DELETE CASCADE,
  CONSTRAINT ACNT_USER_FK_2 FOREIGN KEY (STUS_LKP_CD) REFERENCES BIDDLER_DB.LKP_INFO (LKP_CD)
);

CREATE TABLE BIDDLER_DB.ACNT_USER_ROLE (
  ACNT_ID           INT NOT NULL,
  USER_ID           INT NOT NULL,
  ROLE_ID           VARCHAR(32) NOT NULL,
  STUS_LKP_CD      VARCHAR(32) NOT NULL,
  EFCTV_STRT_DT     DATE DEFAULT NULL,
  EFCTV_END_DT      DATE DEFAULT NULL,
  CREATD_DT         DATETIME NOT NULL, 
  CREATD_BY         VARCHAR(48) NULL DEFAULT 'SYSTEM', 
  LAST_UPDATD_DT    DATETIME NOT NULL, 
  LAST_UPDATD_BY    VARCHAR(48) NULL DEFAULT 'SYSTEM', 
  DLTD_AT           DATETIME NULL DEFAULT NULL, 
  CONSTRAINT ACNT_USER_ROLE_PK    PRIMARY KEY (USER_ID,ACNT_ID,ROLE_ID),
  CONSTRAINT ACNT_USER_ROLE_FK    FOREIGN KEY (ACNT_ID) REFERENCES BIDDLER_DB.ACNT_INFO (ACNT_ID),
  CONSTRAINT ACNT_USER_ROLE_FK_1  FOREIGN KEY (USER_ID) REFERENCES BIDDLER_DB.USER_INFO (USER_ID),
  CONSTRAINT ACNT_USER_ROLE_FK_2  FOREIGN KEY (ROLE_ID) REFERENCES BIDDLER_DB.ROLE_INFO (ROLE_ID),
  CONSTRAINT ACNT_USER_ROLE_FK_3  FOREIGN KEY (STUS_LKP_CD)  REFERENCES BIDDLER_DB.LKP_INFO  (LKP_CD)
) ;

CREATE TABLE BIDDLER_DB.ROLE_PERMSN (
  PERMSN_ID       VARCHAR(32) NOT NULL,
  ROLE_ID         VARCHAR(32) NOT NULL,
  STUS_LKP_CD     VARCHAR(32) NOT NULL,
  EFCTV_STRT_DT   DATE DEFAULT NULL,
  EFCTV_END_DT    DATE DEFAULT NULL,
  CREATD_DT       DATETIME NOT NULL, 
  CREATD_BY       VARCHAR(48) NULL DEFAULT 'SYSTEM', 
  LAST_UPDATD_DT  DATETIME NOT NULL, 
  LAST_UPDATD_BY  VARCHAR(48) NULL DEFAULT 'SYSTEM', 
  DLTD_AT         DATETIME NULL DEFAULT NULL, 
  CONSTRAINT ROLE_PERMSN_PK   PRIMARY KEY (PERMSN_ID, ROLE_ID),
  CONSTRAINT ROLE_PERMSN_FK   FOREIGN KEY (PERMSN_ID) REFERENCES BIDDLER_DB.PERMSN_INFO (PERMSN_ID) ON DELETE CASCADE ON UPDATE RESTRICT,
  CONSTRAINT ROLE_PERMSN_FK_1 FOREIGN KEY (ROLE_ID)  REFERENCES BIDDLER_DB.ROLE_INFO (ROLE_ID) ON DELETE CASCADE ON UPDATE RESTRICT,
  CONSTRAINT ROLE_PERMSN_FK_2 FOREIGN KEY (STUS_LKP_CD)  REFERENCES BIDDLER_DB.LKP_INFO (LKP_CD)
) ;