-- Address Type lookups
INSERT INTO BIDDLER_DB.LKP_INFO (LKP_GRP_NAME, LKP_CD, LKP_TITLE, LKP_DESC, CREATD_DT, LAST_UPDATD_DT)
	VALUES ('addressType', 'home', 'Home', 'Home Address', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO BIDDLER_DB.LKP_INFO (LKP_GRP_NAME, LKP_CD, LKP_TITLE, LKP_DESC, CREATD_DT, LAST_UPDATD_DT)
	VALUES ('addressType', 'business', 'Business', 'Business Address', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO BIDDLER_DB.LKP_INFO (LKP_GRP_NAME, LKP_CD, LKP_TITLE, LKP_DESC, CREATD_DT, LAST_UPDATD_DT)
	VALUES ('addressType', 'billing', 'Billing', 'Billing Address', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO BIDDLER_DB.LKP_INFO (LKP_GRP_NAME, LKP_CD, LKP_TITLE, LKP_DESC, CREATD_DT, LAST_UPDATD_DT)
	VALUES ('addressType', 'shipping', 'Shipping', 'Shipping Address', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO BIDDLER_DB.LKP_INFO (LKP_GRP_NAME, LKP_CD, LKP_TITLE, LKP_DESC, CREATD_DT, LAST_UPDATD_DT)
	VALUES ('addressType', 'contract', 'Contract', 'Contract Address', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO BIDDLER_DB.LKP_INFO (LKP_GRP_NAME, LKP_CD, LKP_TITLE, LKP_DESC, CREATD_DT, LAST_UPDATD_DT)
	VALUES ('addressType', 'ar', 'Accounts Receivable', 'Accounts Receivable', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO BIDDLER_DB.LKP_INFO (LKP_GRP_NAME, LKP_CD, LKP_TITLE, LKP_DESC, CREATD_DT, LAST_UPDATD_DT)
	VALUES ('addressType', 'recipient', 'Recipient', 'Recipient Address', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO BIDDLER_DB.LKP_INFO (LKP_GRP_NAME, LKP_CD, LKP_TITLE, LKP_DESC, CREATD_DT, LAST_UPDATD_DT)
	VALUES ('addressType', 'poBox', 'PO Box', 'Post Office Box Address', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO BIDDLER_DB.LKP_INFO (LKP_GRP_NAME, LKP_CD, LKP_TITLE, LKP_DESC, CREATD_DT, LAST_UPDATD_DT)
	VALUES ('addressType', 'school', 'School', 'School Address', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO BIDDLER_DB.LKP_INFO (LKP_GRP_NAME, LKP_CD, LKP_TITLE, LKP_DESC, CREATD_DT, LAST_UPDATD_DT)
	VALUES ('addressType', 'military', 'Military', 'Military Address', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO BIDDLER_DB.LKP_INFO (LKP_GRP_NAME, LKP_CD, LKP_TITLE, LKP_DESC, CREATD_DT, LAST_UPDATD_DT)
	VALUES ('addressType', 'international', 'Internatinoal', 'International Address', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO BIDDLER_DB.LKP_INFO (LKP_GRP_NAME, LKP_CD, LKP_TITLE, LKP_DESC, CREATD_DT, LAST_UPDATD_DT)
	VALUES ('addressType', 'mailing', 'mailing', 'Mailing Address', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO BIDDLER_DB.LKP_INFO (LKP_GRP_NAME, LKP_CD, LKP_TITLE, LKP_DESC, CREATD_DT, LAST_UPDATD_DT)
	VALUES ('addressType', 'physical', 'phyisical', 'Physical Address', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

-- Status Lookups
INSERT INTO BIDDLER_DB.LKP_INFO (LKP_GRP_NAME, LKP_CD, LKP_TITLE, CREATD_DT, LAST_UPDATD_DT)
	VALUES('status', 'active', 'Active', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO BIDDLER_DB.LKP_INFO (LKP_GRP_NAME, LKP_CD, LKP_TITLE, CREATD_DT, LAST_UPDATD_DT)
	VALUES('status', 'archived', 'Archived', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO BIDDLER_DB.LKP_INFO (LKP_GRP_NAME, LKP_CD, LKP_TITLE, CREATD_DT, LAST_UPDATD_DT)
	VALUES('status', 'cancelled', 'Cancelled', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO BIDDLER_DB.LKP_INFO (LKP_GRP_NAME, LKP_CD, LKP_TITLE, CREATD_DT, LAST_UPDATD_DT)
	VALUES('status', 'closed', 'Closed', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO BIDDLER_DB.LKP_INFO (LKP_GRP_NAME, LKP_CD, LKP_TITLE, CREATD_DT, LAST_UPDATD_DT)
	VALUES('status', 'completed', 'Completed', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO BIDDLER_DB.LKP_INFO (LKP_GRP_NAME, LKP_CD, LKP_TITLE, CREATD_DT, LAST_UPDATD_DT)
	VALUES('status', 'deleted', 'Deleted', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO BIDDLER_DB.LKP_INFO (LKP_GRP_NAME, LKP_CD, LKP_TITLE, CREATD_DT, LAST_UPDATD_DT)
	VALUES('status', 'draft', 'Draft', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO BIDDLER_DB.LKP_INFO (LKP_GRP_NAME, LKP_CD, LKP_TITLE, CREATD_DT, LAST_UPDATD_DT)
	VALUES('status', 'expired', 'Expired', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO BIDDLER_DB.LKP_INFO (LKP_GRP_NAME, LKP_CD, LKP_TITLE, CREATD_DT, LAST_UPDATD_DT)
	VALUES('status', 'failed', 'Failed', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO BIDDLER_DB.LKP_INFO (LKP_GRP_NAME, LKP_CD, LKP_TITLE, CREATD_DT, LAST_UPDATD_DT)
	VALUES('status', 'in progress', 'In Progress', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO BIDDLER_DB.LKP_INFO (LKP_GRP_NAME, LKP_CD, LKP_TITLE, CREATD_DT, LAST_UPDATD_DT)
	VALUES('status', 'new', 'New', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO BIDDLER_DB.LKP_INFO (LKP_GRP_NAME, LKP_CD, LKP_TITLE, CREATD_DT, LAST_UPDATD_DT)
	VALUES('status', 'open', 'Open', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO BIDDLER_DB.LKP_INFO (LKP_GRP_NAME, LKP_CD, LKP_TITLE, CREATD_DT, LAST_UPDATD_DT)
	VALUES('status', 'pending', 'Pending', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO BIDDLER_DB.LKP_INFO (LKP_GRP_NAME, LKP_CD, LKP_TITLE, CREATD_DT, LAST_UPDATD_DT)
	VALUES('status', 'processing', 'Processing', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO BIDDLER_DB.LKP_INFO (LKP_GRP_NAME, LKP_CD, LKP_TITLE, CREATD_DT, LAST_UPDATD_DT)
	VALUES('status', 'reviewed', 'Record has been reviewed', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO BIDDLER_DB.LKP_INFO (LKP_GRP_NAME, LKP_CD, LKP_TITLE, CREATD_DT, LAST_UPDATD_DT)
	VALUES('status', 'revoked', 'Revoked', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO BIDDLER_DB.LKP_INFO (LKP_GRP_NAME, LKP_CD, LKP_TITLE, CREATD_DT, LAST_UPDATD_DT)
	VALUES('status', 'suspended', 'Suspended', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO BIDDLER_DB.LKP_INFO (LKP_GRP_NAME, LKP_CD, LKP_TITLE, CREATD_DT, LAST_UPDATD_DT)
	VALUES('status', 'under construction', 'Under Construction', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
