CREATE TABLE BIDDLER_DB.CAMPGN_INFO (
	CMPGN_ID        INT auto_increment NOT NULL,
	USER_ID         INT NOT NULL,
  CAMPGN_GOAL_LKP_ID  VARCHAR(32) NOT NULL,
  CAMPGN_TYP_LKP_ID   VARCHAR(32) NOT NULL,
	STUS_LKP_ID     VARCHAR(32) NOT NULL,
  CMPGN_NAME      VARCHAR(128) NOT NULL, 
  EFCTV_STRT_DT   DATE DEFAULT NULL,
  EFCTV_END_DT    DATE DEFAULT NULL,    
  META_INFO       JSON NULL,
  CREATD_DT       DATETIME NOT NULL, 
  CREATD_BY       VARCHAR(48) NULL DEFAULT 'SYSTEM', 
  LAST_UPDATD_DT  DATETIME NOT NULL, 
  LAST_UPDATD_BY  VARCHAR(48) NULL DEFAULT 'SYSTEM', 
  DLTD_AT         DATETIME NULL DEFAULT NULL, 
	CONSTRAINT CAMPGN_INFO_PK   PRIMARY KEY (CMPGN_ID),
  CONSTRAINT CAMPGN_INFO_FK   FOREIGN KEY (STUS_LKP_ID)         REFERENCES BIDDLER_DB.LKP_INFO(LKP_ID),
	CONSTRAINT CAMPGN_INFO_FK_1 FOREIGN KEY (USER_ID)             REFERENCES BIDDLER_DB.USER_INFO(USER_ID),
  CONSTRAINT CAMPGN_INFO_FK_2 FOREIGN KEY (CAMPGN_GOAL_LKP_ID)  REFERENCES BIDDLER_DB.LKP_INFO(LKP_ID),
  CONSTRAINT CAMPGN_INFO_FK_3 FOREIGN KEY (CAMPGN_TYP_LKP_ID)   REFERENCES BIDDLER_DB.LKP_INFO(LKP_ID)
);

-- CREATE TABLE BIDDLER_DB.CAMPGN_RSLTS (
-- 	CMPGN_ID        INT NOT NULL,
--   RSLTS_LKP_ID    VARCHAR(32) NOT NULL,
-- 	STUS_LKP_ID     VARCHAR(32) NOT NULL,
--   CNTNT           VARCHAR(512) NOT NULL,
--   EFCTV_STRT_DT   DATE DEFAULT NULL,
--   EFCTV_END_DT    DATE DEFAULT NULL,
--   CREATD_DT       DATETIME NOT NULL, 
--   CREATD_BY       VARCHAR(48) NULL DEFAULT 'SYSTEM', 
--   LAST_UPDATD_DT  DATETIME NOT NULL, 
--   LAST_UPDATD_BY  VARCHAR(48) NULL DEFAULT 'SYSTEM', 
--   DLTD_AT         DATETIME NULL DEFAULT NULL, 
-- 	CONSTRAINT CAMPGN_RSLTS_PK   PRIMARY KEY (CMPGN_ID, RSLTS_LKP_ID),
--   CONSTRAINT CAMPGN_RSLTS_FK   FOREIGN KEY (STUS_LKP_ID)   REFERENCES BIDDLER_DB.LKP_INFO(LKP_ID),
--   CONSTRAINT CAMPGN_RSLTS_FK_1 FOREIGN KEY (RSLTS_LKP_ID)  REFERENCES BIDDLER_DB.LKP_INFO(LKP_ID),
--   CONSTRAINT CAMPGN_RSLTS_FK_2 FOREIGN KEY (CMPGN_ID)      REFERENCES BIDDLER_DB.CAMPGN_INFO(CMPGN_ID)
-- );

-- CREATE TABLE BIDDLER_DB.CAMPGN_NTWKS (
-- 	CMPGN_ID        INT NOT NULL,
--   NTWKS_LKP_ID    VARCHAR(32) NOT NULL,
-- 	STUS_LKP_ID     VARCHAR(32) NOT NULL,
--   CNTNT           VARCHAR(512) NOT NULL,
--   EFCTV_STRT_DT   DATE DEFAULT NULL,
--   EFCTV_END_DT    DATE DEFAULT NULL,
--   CREATD_DT       DATETIME NOT NULL, 
--   CREATD_BY       VARCHAR(48) NULL DEFAULT 'SYSTEM', 
--   LAST_UPDATD_DT  DATETIME NOT NULL, 
--   LAST_UPDATD_BY  VARCHAR(48) NULL DEFAULT 'SYSTEM', 
--   DLTD_AT         DATETIME NULL DEFAULT NULL, 
-- 	CONSTRAINT CAMPGN_NTWKS_PK  PRIMARY KEY (CMPGN_ID, RSLTS_LKP_ID),
--   CONSTRAINT CAMPGN_NTWKS_FK  FOREIGN KEY (STUS_LKP_ID)   REFERENCES BIDDLER_DB.LKP_INFO(LKP_ID),
--   CONSTRAINT CAMPGN_NTWKS_1   FOREIGN KEY (RSLTS_LKP_ID)  REFERENCES BIDDLER_DB.LKP_INFO(LKP_ID),
--   CONSTRAINT CAMPGN_NTWKS_2   FOREIGN KEY (CMPGN_ID)      REFERENCES BIDDLER_DB.CAMPGN_INFO(CMPGN_ID)
-- );