-- Status Lookups
INSERT INTO BIDDLER_IDM_DB.LKP_INFO (LKP_GRP_NAME, LKP_CD, LKP_ID, LKP_TITLE, CREATD_DT, LAST_UPDATD_DT)
	VALUES('status', 'active', 'st_active','Active', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO BIDDLER_IDM_DB.LKP_INFO (LKP_GRP_NAME, LKP_CD, LKP_ID, LKP_TITLE, CREATD_DT, LAST_UPDATD_DT)
	VALUES('status', 'archived', 'st_archived', 'Archived', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO BIDDLER_IDM_DB.LKP_INFO (LKP_GRP_NAME, LKP_CD, LKP_ID, LKP_TITLE, CREATD_DT, LAST_UPDATD_DT)
	VALUES('status', 'cancelled', 'st_cancelled', 'Cancelled', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO BIDDLER_IDM_DB.LKP_INFO (LKP_GRP_NAME, LKP_CD, LKP_ID, LKP_TITLE, CREATD_DT, LAST_UPDATD_DT)
	VALUES('status', 'closed', 'st_closed','Closed', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO BIDDLER_IDM_DB.LKP_INFO (LKP_GRP_NAME, LKP_CD, LKP_ID, LKP_TITLE, CREATD_DT, LAST_UPDATD_DT)
	VALUES('status', 'completed', 'st_completed','Completed', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO BIDDLER_IDM_DB.LKP_INFO (LKP_GRP_NAME, LKP_CD, LKP_ID, LKP_TITLE, CREATD_DT, LAST_UPDATD_DT)
	VALUES('status', 'deleted', 'st_deleted','Deleted', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO BIDDLER_IDM_DB.LKP_INFO (LKP_GRP_NAME, LKP_CD, LKP_ID, LKP_TITLE, CREATD_DT, LAST_UPDATD_DT)
	VALUES('status', 'draft', 'st_draft','Draft', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO BIDDLER_IDM_DB.LKP_INFO (LKP_GRP_NAME, LKP_CD, LKP_ID, LKP_TITLE, CREATD_DT, LAST_UPDATD_DT)
	VALUES('status', 'expired', 'st_expired','Expired', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO BIDDLER_IDM_DB.LKP_INFO (LKP_GRP_NAME, LKP_CD, LKP_ID, LKP_TITLE, CREATD_DT, LAST_UPDATD_DT)
	VALUES('status', 'failed', 'st_failed','Failed', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO BIDDLER_IDM_DB.LKP_INFO (LKP_GRP_NAME, LKP_CD, LKP_ID, LKP_TITLE, CREATD_DT, LAST_UPDATD_DT)
	VALUES('status', 'in progress', 'st_in progress', 'In Progress', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO BIDDLER_IDM_DB.LKP_INFO (LKP_GRP_NAME, LKP_CD, LKP_ID, LKP_TITLE, CREATD_DT, LAST_UPDATD_DT)
	VALUES('status', 'new', 'st_new','New', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO BIDDLER_IDM_DB.LKP_INFO (LKP_GRP_NAME, LKP_CD, LKP_ID, LKP_TITLE, CREATD_DT, LAST_UPDATD_DT)
	VALUES('status', 'open', 'st_open','Open', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO BIDDLER_IDM_DB.LKP_INFO (LKP_GRP_NAME, LKP_CD, LKP_ID, LKP_TITLE, CREATD_DT, LAST_UPDATD_DT)
	VALUES('status', 'pending', 'st_pending','Pending', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO BIDDLER_IDM_DB.LKP_INFO (LKP_GRP_NAME, LKP_CD, LKP_ID, LKP_TITLE, CREATD_DT, LAST_UPDATD_DT)
	VALUES('status', 'processing','st_processing', 'Processing', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO BIDDLER_IDM_DB.LKP_INFO (LKP_GRP_NAME, LKP_CD, LKP_ID, LKP_TITLE, CREATD_DT, LAST_UPDATD_DT)
	VALUES('status', 'reviewed', 'st_reviewed','Record has been reviewed', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO BIDDLER_IDM_DB.LKP_INFO (LKP_GRP_NAME, LKP_CD, LKP_ID, LKP_TITLE, CREATD_DT, LAST_UPDATD_DT)
	VALUES('status', 'revoked', 'st_revoked', 'Revoked', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO BIDDLER_IDM_DB.LKP_INFO (LKP_GRP_NAME, LKP_CD, LKP_ID, LKP_TITLE, CREATD_DT, LAST_UPDATD_DT)
	VALUES('status', 'suspended', 'st_suspended', 'Suspended', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO BIDDLER_IDM_DB.LKP_INFO (LKP_GRP_NAME, LKP_CD, LKP_ID, LKP_TITLE, CREATD_DT, LAST_UPDATD_DT)
	VALUES('status', 'under construction', 'st_under construction', 'Under Construction', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

  -- TOKEN TYPE:: ACS_TOKN
  INSERT INTO BIDDLER_IDM_DB.LKP_INFO (LKP_GRP_NAME, LKP_CD, LKP_ID, LKP_TITLE, CREATD_DT, LAST_UPDATD_DT)
	VALUES('tokenType', 'jwt', 'tt_jwt', 'Self-signed JWT', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
  INSERT INTO BIDDLER_IDM_DB.LKP_INFO (LKP_GRP_NAME, LKP_CD, LKP_ID, LKP_TITLE, CREATD_DT, LAST_UPDATD_DT)
	VALUES('tokenType', 'access', 'tt_access', 'Access Token', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
  INSERT INTO BIDDLER_IDM_DB.LKP_INFO (LKP_GRP_NAME, LKP_CD, LKP_ID, LKP_TITLE, CREATD_DT, LAST_UPDATD_DT)
	VALUES('tokenType', 'id', 'tt_id', 'ID Token', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
  INSERT INTO BIDDLER_IDM_DB.LKP_INFO (LKP_GRP_NAME, LKP_CD, LKP_ID, LKP_TITLE, CREATD_DT, LAST_UPDATD_DT)
	VALUES('tokenType', 'refresh', 'tt_refresh', 'Refresh Token', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
  INSERT INTO BIDDLER_IDM_DB.LKP_INFO (LKP_GRP_NAME, LKP_CD, LKP_ID, LKP_TITLE, CREATD_DT, LAST_UPDATD_DT)
	VALUES('tokenType', 'bearer', 'tt_bearer', 'Bearer Token', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
  INSERT INTO BIDDLER_IDM_DB.LKP_INFO (LKP_GRP_NAME, LKP_CD, LKP_ID, LKP_TITLE, CREATD_DT, LAST_UPDATD_DT)
	VALUES('tokenType', 'federated', 'tt_federated', 'Federated Token', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

-- Scheme Type : ACS_TKN
  INSERT INTO BIDDLER_IDM_DB.LKP_INFO (LKP_GRP_NAME, LKP_CD, LKP_ID, LKP_TITLE, CREATD_DT, LAST_UPDATD_DT)
	VALUES('tokenSchemeType', 'ascii', 'tst_ascii', 'ASCII', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
  INSERT INTO BIDDLER_IDM_DB.LKP_INFO (LKP_GRP_NAME, LKP_CD, LKP_ID, LKP_TITLE, CREATD_DT, LAST_UPDATD_DT)
	VALUES('tokenSchemeType', 'pci', 'tst_pci', 'PCI ', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

-- System Info
INSERT INTO BIDDLER_IDM_DB.SYS_INFO
(SYS_ID, STUS_LKP_ID, SYS_NAME, SYS_NAME_SLUG, SYS_DESC, SYS_URL, EFCTV_STRT_DT, EFCTV_END_DT, CREATD_DT, CREATD_BY, LAST_UPDATD_DT, LAST_UPDATD_BY, DLTD_AT)
VALUES(1, 'st_active', 'BiddlerApi', 'biddler-api', 'The api for the biddler application', 'localhost:8080/v1', '2023-01-01 00:00:00', '2024-01-01 00:00:00', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', NULL);

INSERT INTO BIDDLER_IDM_DB.SYS_ISSUER
(SYS_ISSUER_ID, SYS_ID, STUS_LKP_ID, TOKN_TYP_LKP_ID, ISSUER_NAME, TKN_TTL, RFRSH_TKN_TTL, HASH_ALGORITHM, ORIGIN, RESTRICTED_IPS, ALLOWED_IPS, METHODS, ALLOWED_HEADERS, EXPOSED_HEADERS, ALLOW_CREDENTIALS, MAX_AGE_SECONDS, CREATD_DT, CREATD_BY, LAST_UPDATD_DT, LAST_UPDATD_BY, DLTD_AT)
VALUES(1, 1, 'st_active', 'tt_jwt', 'magic', 60, 259200, 'HS256', '*', NULL, NULL, 'GET,POST,PUT,PATCH', NULL, NULL, 1, 60, CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', NULL);